export const kidsData = [
  {
      "id": "26",
      "product": "Kids Wear",
      "image": "/src/assets/Kids/13.png",
      "type": "Shirt",
      "brand": "H&M",
      "model": "Casual Kids Shirt",
      "cprice": "1290.99",
        "discount":"60",
        "rating":"5",
        "sprice" :"510.99", 
      "category": "Clothing",
      "description": "A lightweight casual shirt perfect for summer outings."
  },
  {
      "id": "27",
      "product": "Kids Wear",
      "image": "/src/assets/Kids/14.png",
      "type": "Jeans",
      "brand": "Levi's",
      "model": "Kids Denim Jeans",
      "cprice": "599.50",
      "discount":"60",
      "rating":"5",
     "sprice" :"239.50", 
      "category": "Clothing",
      "description": "Durable and stylish jeans for kids, suitable for all seasons."
  },
  {
      "id": "28",
      "product": "Kids Wear",
      "image": "/src/assets/Kids/15.png",
      "type": "Sneakers",
      "brand": "Nike",
      "model": "Air Max Kids",
      "cprice": "499.99",
      "discount": "60",
      "rating": "4",
      "sprice": "199.90",
      "category": "Footwear",
      "description": "Trendy sneakers offering comfort and support for active kids."
  },
  {
      "id": "29",
      "product": "Kids Wear",
      "image": "/src/assets/Kids/16.png",
      "type": "Jacket",
      "brand": "Zara",
      "model": "Winter Kids Jacket",
      "cprice": "699.00",
      "discount":"60",
      "rating":"3",
      "sprice" :"129.50", 
      "category": "Clothing",
      "description": "A warm and cozy jacket to keep your kids comfortable in cold weather."
  },
  {
      "id": "30",
      "product": "Kids Wear",
      "image": "/src/assets/Kids/17.png",
      "type": "Shorts",
      "brand": "Adidas",
      "model": "Kids Active Shorts",
      "cprice": "1299.99",
        "discount":"40",
        "rating":"5",
       "sprice":"779.50", 
      "category": "Clothing",
      "description": "Lightweight and breathable shorts for active kids."
  },
  {
      "id": "31",
      "product": "Kids Wear",
      "image": "/src/assets/Kids/18.png",
      "type": "T-shirt",
      "brand": "Puma",
      "model": "Graphic Kids Tee",
    "cprice": "3499.99",
       "discount":"30",
       "rating":"4",
       "sprice" :"2449.50", 
      "category": "Clothing",
      "description": "A fun and colorful t-shirt perfect for everyday casual wear."
  },
  {
      "id": "32",
      "product": "Kids Wear",
      "image": "/src/assets/Kids/19.png",
      "type": "Dress",
      "brand": "GAP",
      "model": "Floral Kids Dress",
     "cprice": "799.50",
       "discount":"40",
       "rating":"5",
       "sprice" :"479.50",
      "category": "Clothing",
      "description": "A beautiful floral dress for special occasions."
  },
  {
      "id": "33",
      "product": "Kids Wear",
      "image": "/src/assets/Kids/20.png",
      "type": "Cap",
      "brand": "Nike",
      "model": "Kids Sports Cap",
     "cprice": "1599.00",
        "discount":"30",
        "rating":"3",
        "sprice":"1119.50", 
      "category": "Accessories",
      "description": "A stylish and comfortable cap for outdoor activities."
  },
  {
      "id": "34",
      "product": "Kids Wear",
      "image": "/src/assets/Kids/21.png",
      "type": "Socks",
      "brand": "Adidas",
      "model": "Ankle Socks",
     "cprice": "440.99",
        "discount":"40",
        "rating":"4",
        "sprice" :"264.50",
      "category": "Accessories",
      "description": "Soft and comfortable socks for everyday wear."
  },
  {
      "id": "35",
      "product": "Kids Wear",
      "image": "/src/assets/Kids/22.png",
      "type": "Boots",
      "brand": "Timberland",
      "model": "Kids Hiking Boots",
      "cprice": "3999.99",
       "discount":"30",
       "rating":"5",
       "sprice" :"2799.50", 
      "category": "Footwear",
      "description": "Sturdy and durable hiking boots for adventurous kids."
  },
  {
      "id": "36",
      "product": "Kids Wear",
      "image": "/src/assets/Kids/23.png",
      "type": "Sunglasses",
      "brand": "Ray-Ban",
      "model": "Kids Aviators",
      "cprice": "2999.50",
     "discount":"40",
     "rating":"4",
    "sprice" :"1799.50",  
      "category": "Accessories",
      "description": "Stylish sunglasses offering full UV protection for kids."
  },
  {
      "id": "37",
      "product": "Kids Wear",
      "image": "/src/assets/Kids/24.png",
      "type": "Gloves",
      "brand": "The North Face",
      "model": "Winter Kids Gloves",
      "cprice": "1399.00",
      "discount":"60",
      "rating":"3",
      "sprice":"1329.50", 
      "category": "Accessories",
      "description": "Warm gloves to keep little hands cozy in winter."
  },
  {
      "id": "38",
      "product": "Kids Wear",
      "image": "/src/assets/Kids/25.png",
      "type": "Backpack",
      "brand": "Nike",
      "model": "Kids School Backpack",
      "cprice": "1290.99",
        "discount":"60",
        "rating":"4",
        "sprice" :"510.99", 
      "category": "Accessories",
      "description": "A durable and spacious backpack for school and outings."
  },
  {
      "id": "39",
      "product": "Kids Wear",
      "image": "/src/assets/Kids/26.png",
      "type": "Raincoat",
      "brand": "H&M",
      "model": "Kids Waterproof Raincoat",
      "cprice": "499.99",
        "discount":"60",
        "rating":"5",
        "sprice" :"199.90", 
      "category": "Clothing",
      "description": "A waterproof raincoat to keep kids dry during rainy days."
  },
  {
      "id": "40",
      "product": "Kids Wear",
      "image": "/src/assets/Kids/27.png",
      "type": "Pyjama Set",
      "brand": "Disney",
      "model": "Mickey Mouse Pyjamas",
      "cprice": "599.50",
      "discount":"60",
      "rating":"5",
      "sprice" :"239.50",
      "category": "Clothing",
      "description": "Comfortable and fun pyjama set for a cozy sleep."
  },
  {
      "id": "41",
      "product": "Kids Wear",
      "image": "/src/assets/Kids/28.png",
      "type": "Trousers",
      "brand": "Zara",
      "model": "Kids Cargo Pants",
      "cprice": "699.00",
       "discount":"60",
       "rating":"4",
       "sprice" :"129.50", 
      "category": "Clothing",
      "description": "Stylish cargo pants perfect for active kids."
  },
  {
      "id": "42",
      "product": "Kids Wear",
      "image": "/src/assets/Kids/29.png",
      "type": "Sweater",
      "brand": "GAP",
      "model": "Kids Winter Sweater",
     "cprice": "1299.99",
        "discount":"40",
        "rating":"3",
        "sprice":"779.50", 
      "category": "Clothing",
      "description": "A warm and cozy sweater for chilly winter days."
  },
  {
    "id": "43",
    "product": "Kids Wear",
    "image": "/src/assets/Kids/30.png",
    "type": "Hoodie",
    "brand": "Nike",
    "model": "Kids Fleece Hoodie",
   "cprice": "3499.99",
        "discount":"30",
        "rating":"4",
        "sprice" :"2449.50", 
    "category": "Clothing",
    "description": "A comfortable fleece hoodie, perfect for casual wear."
},
{
    "id": "44",
    "product": "Kids Wear",
    "image": "/src/assets/Kids/31.png",
    "type": "Slippers",
    "brand": "Puma",
    "model": "Kids Slide Slippers",
    "cprice": "799.50",
    "discount":"40",
    "rating":"5",
    "sprice" :"479.50", 
    "category": "Footwear",
    "description": "Easy-to-wear slide slippers for home and outdoor use."
},
{
    "id": "45",
    "product": "Kids Wear",
    "image": "/src/assets/Kids/32.png",
    "type": "Tracksuit",
    "brand": "Adidas",
    "model": "Kids Sports Tracksuit",
    "cprice": "1599.00",
       "discount":"30",
       "rating":"5",
       "sprice":"1119.50", 
    "category": "Clothing",
    "description": "A comfortable tracksuit for active sports and casual wear."
},
{
    "id": "46",
    "product": "Kids Wear",
    "image": "/src/assets/Kids/33.png",
    "type": "Rain Boots",
    "brand": "Hunter",
    "model": "Kids Waterproof Boots",
    "cprice": "440.99",
        "discount":"40",
        "rating":"4",
        "sprice" :"264.50",
    "category": "Footwear",
    "description": "Durable rain boots perfect for wet conditions."
},
{
    "id": "47",
    "product": "Kids Wear",
    "image": "/src/assets/Kids/34.png",
    "type": "Hat",
    "brand": "Gap",
    "model": "Kids Sun Hat",
    "cprice": "3999.99",
    "discount":"30",
    "rating":"4",
    "sprice" :"2799.50", 
    "category": "Accessories",
    "description": "A stylish and protective sun hat for outdoor play."
},
{
    "id": "48",
    "product": "Kids Wear",
    "image": "/src/assets/Kids/35.png",
    "type": "Swimsuit",
    "brand": "Speedo",
    "model": "Kids Swimwear",
    "cprice": "1200.00",
    "discount": "18",
    "rating": "4.6",
    "sprice": "1500.00",
    "category": "Clothing",
    "description": "Durable and comfortable swimsuit for pool and beach."
},
{
    "id": "49",
    "product": "Kids Wear",
    "image": "/src/assets/Kids/36.png",
    "type": "Puffer Jacket",
    "brand": "The North Face",
    "model": "Kids Insulated Puffer",
    "cprice": "3000.00",
    "discount": "25",
    "rating": "4.9",
    "sprice": "3000.00",
    "category": "Clothing",
    "description": "Insulated puffer jacket for warmth in extreme cold."
},
{
    "id": "50",
    "product": "Kids Wear",
    "image": "/src/assets/Kids/13.png",
    "type": "Flip-Flops",
    "brand": "Havaianas",
    "model": "Kids Beach Flip-Flops",
    "cprice": "1899.00",
        "discount":"30",
        "rating":"3",
        "sprice":"1329.50", 
    "category": "Footwear",
    "description": "Comfortable flip-flops for beach days."
},
{
    "id": "51",
    "product": "Kids Wear",
    "image": "/src/assets/Kids/14.png",
    "type": "Joggers",
    "brand": "Reebok",
    "model": "Kids Fleece Joggers",
   "cprice": "1899.00",
        "discount":"30",
        "rating":"3",
        "sprice":"1329.50", 
    "category": "Clothing",
    "description": "Comfortable joggers perfect for sports and lounging."
},
{
    "id": "52",
    "product": "Kids Wear",
    "image": "/src/assets/Kids/15.png",
    "type": "Leggings",
    "brand": "Zara",
    "model": "Kids Printed Leggings",
   "cprice": "1899.00",
        "discount":"30",
        "rating":"5",
        "sprice":"1329.50", 
    "category": "Clothing",
    "description": "Soft and stretchy leggings with fun prints for everyday wear."
},
{
    "id": "53",
    "product": "Kids Wear",
    "image": "/src/assets/Kids/16.png",
    "type": "Sweatshirt",
    "brand": "H&M",
    "model": "Graphic Kids Sweatshirt",
   "cprice": "1899.00",
        "discount":"30",
        "rating":"5",
        "sprice":"1329.50", 
    "category": "Clothing",
    "description": "A cozy graphic sweatshirt for cool days."
},
{
    "id": "54",
    "product": "Kids Wear",
    "image": "/src/assets/Kids/17.png",
    "type": "Scarf",
    "brand": "Uniqlo",
    "model": "Winter Kids Scarf",
    "cprice": "1899.00",
        "discount":"30",
        "rating":"4",
        "sprice":"1329.50", 
    "category": "Accessories",
    "description": "A warm and soft scarf to keep kids cozy during winter."
}
];

  
